entpay:
  base-url: https://dev-api-business.tenpay.com
  platform-id: 4010020301278100
  platform-private-cert-serial-no: 542A49BD51D0E2B8660431B8B942CDFB8FBE7ACB
  tbep-serial-no: 23DCF685F1E9F7EE732AB3D9B8AA64BBD8A91106
  tbep-public-key: |
    -----BEGIN RSA PUBLIC KEY-----
    MIIBCgKCAQEAubADF7+Tr1WSQQQkeCq4qT/TIt1dxNj5LdIEVCZhYBHuA/cgEEAY
    HsWZutmAFx9w8PAQBDEkK+W9/0f+KYafjgFHplGiStdTTUq3qJKeS4lVK9RTXp+7
    o9wYQSFk0wAQu56SxRs7NIBtF17eUQqUU/bLqa9JiVgh2zEFKgOpC+M504RKAP1O
    LeHL9wYjll88z8w40TytLjWXR5tuEfjYJlebI2AbNwdcChXKcnM7/08xq2UltBQ+
    qn6a+FyITpg2A7m+M6xp6PAiV2/Xx4P4EW5Pr6mwWBKaYm21R6cjhPRg0qdQkOPW
    NGfNJM01wKMOmCrTERH3+BrIeOXz5symvQIDAQAB
    -----END RSA PUBLIC KEY-----
  platform-private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA2Ir9OhahgHIJW3o651ZQWxLezJsc9KnJbotxU0yvJ6MWMLdy
    5mvEYQ0Ub2ZRGnUCO0Lkdh69rWysOZWTfaMuXjrSvuGBr0oFpOIHT3zu8ySm+USr
    xlq+SP5ynyqT5b0Uss2A5atGarWqccihw9cduyN4xsectN1Gqp8u6zQK9Xxsw8md
    8rKxNL1Qi0A3N2cz2iBVqCdlU70rCtsQWaea6o2K1amXkxyUG+dshic6XvIi7hJ5
    pLOVgTyOA9fSzgYW1xnIgN+byoy1LFaOrp+SYnIrIhrundtZLvGuRBSK6aDCYLZi
    AcgSJaXZUeHGnSCdl15ttU1M7Ns6ADmq9Gu26wIDAQABAoIBAQCjPZwKN1dGmjEd
    qfZPwQzQq1gUTHa2pmw4jpw+3JdKPTKURSc0N1eShia6mBpZ5I1rGVFbDm+VFlB7
    FJxcYTCqTpPi2+NEvnukwdQbAyarWx0Y2sDXxj6ejlrgTFu0HCdHZ45dFRH/jbXR
    ExuHpFpAYkxBJeennQwRwfC/1LrSNbdu3excY6RqAhK9jv1KFBPQm1xKNvG/gTIg
    6dKxcEVm1FQQvt8zbNC9X4Rlov/B4JbTmJbqVUdCOOjyTexTz8icZaIOqLrb6EF7
    YoL3iWH2gyG1L2IfTksLRVkV7axP8HSttsmIwk13g5vxYf9EyoGOba13RTO1Pe9o
    P4FmP/RpAoGBAPzrcdLVbcjKF7s0RDabMD14KklZdrC2/k9PZcbZN4J1WiCYzrC5
    6zJdH3wQcYs5Wx+IUwyPLcN3s29MVKfk3u4ibdd2BOPI4uSuJLbZGY0LICcZnAJV
    gWseUArsfmqmgvcKjTIfz649oOziL5Yo1TcyPsSle9kEP/KfPxov66BNAoGBANsu
    IPHAmwHkNhSaciJ7fZgel+slnoNNH9m/QwGdezSyhaNdeqm7/oCR6WNbb8a9VUPD
    WjHLwBsck82/QSO9nwosqYD7dfQYTSoPUUntyEFlqFSrJyI4W8h9ZHd5BmKuxues
    mAGGVAgudqnzUNU00K5Oc+OMJ2QHmuhV+S8O6ZAXAoGAalYLOxtk1wCwzZKCA3tn
    4tA85y3oCxBFB89X+SymfAEe7YmRjRf93OTuMdkwA9sPhshoMmWYVhBjrq2nAhfl
    6rUq/WWvVJ3HV2IoKYBJj9VXpVjNEOYmTYUnHhCkbe6oLXmQN7zMMnPSzwWiAD4W
    tug3H7J7yZhR0o5Fl5sCNBkCgYEA0nKyMy2qJ+DFhHbfC/jimMMXPzL5xjyxTlP0
    tIJPIEQhSMCi3IKjVTPEkh/jbUGxssTJv3JRXDbOPAldNEIHiK9leXD4yozi2nWm
    qYNkelZvkAxeIN9YUWMEqipMVUhXt27i7OPbn5dtXLVBcdWqYRL29w9FayhaNqcG
    AYch/7UCgYBKp8etY8fOfbbY8t2YSsAcxFDW78yFUalT7cSSfn0huAcajDFFrQG7
    fu4pynE5+6uWQiwU3/LqlL7/apALKOiaa9WnFdv0qrgR1x+9opvLLecKliSvjQLn
    lGQycYtZeGbMYXDRg3rGvkvLvPAPfUqroboGdzuiSYfwmptGjwFgYA==
    -----END RSA PRIVATE KEY-----